FROM node:22-alpine3.19

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
# COPY tools ./tools
RUN ls -a

RUN npm install -g npm@10.8.2
RUN npm install  && npm install -g nodemon

EXPOSE 4001

CMD [ "npm", "run", "dev" ]